# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels: ["github_actions", "dependencies"]
    groups:
      actions-minor-and-patch:
        update-types: ["minor", "patch"]
      actions-majors:
        update-types: ["major"]

  - package-ecosystem: "nuget"
    directory: "/XtermBlazor"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels: [".NET", "dependencies"]
    groups:
      nuget-minor-and-patch:
        update-types: ["minor", "patch"]
      nuget-majors:
        update-types: ["major"]

  - package-ecosystem: "npm"
    directory: "/XtermBlazor/src"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels: ["javascript", "dependencies"]
    groups:
      npm-minor-and-patch:
        update-types: ["minor", "patch"]
      npm-majors:
        update-types: ["major"]
    versioning-strategy: increase
